export const suggestions = [
    "Agriculture",
    "Animal Care",
    "Automobile Repair",
    "Bakery",
    "Bricklaying",
    "Carpentry",
    "Cleaning and Maintenance",
    "Construction",
    "Courier Services",
    "Customer Service",
    "Domestic Help",
    "Electrician Services",
    "Event Management",
    "Factory Work",
    "Fishing",
    "Food Processing",
    "Food Service",
    "Forestry",
    "Garment Manufacturing",
    "Gardening",
    "Handicrafts",
    "Healthcare Assistance",
    "Hospitality",
    "House Painting",
    "Janitorial Services",
    "Landscaping",
    "Laundry Services",
    "Logistics",
    "Machinery Operation",
    "Manufacturing",
    "Mechanic",
    "Metalwork",
    "Mining",
    "Packaging",
    "Pest Control",
    "Plumbing",
    "Printing",
    "Recycling",
    "Retail",
    "Road Maintenance",
    "Security Services",
    "Sewing and Tailoring",
    "Shipping and Receiving",
    "Textile Industry",
    "Tourism Assistance",
    "Transportation",
    "Vehicle Washing",
    "Warehousing",
    "Waste Management",
    "Woodworking"
];

export const cities = [
    "Agra",
    "Aligarh",
    "Allahabad",
    "Amroha",
    "Auraiya",
    "Azamgarh",
    "Baghpat",
    "Bahraich",
    "Ballia",
    "Balrampur",
    "Banda",
    "Barabanki",
    "Bareilly",
    "Basti",
    "Bhadohi",
    "Bijnor",
    "Budaun",
    "Bulandshahr",
    "Chandauli",
    "Chitrakoot",
    "Deoria",
    "Etah",
    "Etawah",
    "Faizabad",
    "Farrukhabad",
    "Fatehpur",
    "Firozabad",
    "Gautam Buddh Nagar",
    "Ghaziabad",
    "Ghazipur",
    "Gonda",
    "Gorakhpur",
    "Hamirpur",
    "Hapur",
    "Hardoi",
    "Hathras",
    "Jalaun",
    "Jaunpur",
    "Jhansi",
    "Kannauj",
    "Kanpur",
    "Kasganj",
    "Kaushambi",
    "Kushinagar",
    "Lakhimpur Kheri",
    "Lalitpur",
    "Lucknow",
    "Maharajganj",
    "Mahoba",
    "Mainpuri",
    "Mathura",
    "Mau",
    "Meerut",
    "Mirzapur",
    "Moradabad",
    "Muzaffarnagar",
    "Pilibhit",
    "Pratapgarh",
    "Raebareli",
    "Rampur",
    "Saharanpur",
    "Sambhal",
    "Sant Kabir Nagar",
    "Shahjahanpur",
    "Shamli",
    "Shrawasti",
    "Siddharthnagar",
    "Sitapur",
    "Sonbhadra",
    "Sultanpur",
    "Unnao",
    "Varanasi"
];